[package]
name = "tag-helper"
version = "0.2.1"
description = "Increments semver-compatible git tags"
repository = "https://github.com/panoptix-za/tag-helper"
license = "MIT/Apache-2.0"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["git"]
authors = ["Tshepang Lekhonkhobe <tshepang@gmail.com>"]

[dependencies]
git2 = "0.6"
semver = "0.7"
structopt = "0.1"
structopt-derive = "0.1"

[badges]
travis-ci = { repository = "panoptix-za/tag-helper" }
